name: Тестирование и развертывание проектов

on:
  push:
    branches: [video]

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DUBUG: "0"
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    services:
      postgresql_main:
        image: postgres:12
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready 
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Проверка репозитория на изменения
        uses: actions/checkout@v3

      - name: Установка python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Установка зависимостей
        run: pip install -r 3.2-crud/stocks_products/requirements.txt

      - name: Линтинг
        run: flake8 3.2-crud/stocks_products/logistic/  --exclude=3.2-crud/stocks_products/logistic/migrations/

      - name: Тесты
        run: python 3.2-crud/stocks_products/manage.py test
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
          DUBUG: ${{ env.DUBUG }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DB_ENGINE: ${{ env.DB_ENGINE }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_NAME: ${{ env.DB_NAME }}

      - name: Деплой
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
#          script: |
#            cd /HW_Django/3.2-crud/stocks_products
#            git pull origin video
#            python manage.py migrate
#            sudo systemctl restart gunicorn